import type { Metadata } from "next";
import StyledComponentsRegistry from "@/lib/registry";
import AppBar from "@/components/AppBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          {children}
          <AppBar/>
          </StyledComponentsRegistry>
      </body>
    </html>
  );
}
